// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "VXLIB_accumulateWeightImage_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
#include "test_data/staticRefCase7.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
#include "test_data/staticRefCase8.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
#include "test_data/staticRefCase9.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
#include "test_data/staticRefCase10.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
#include "test_data/staticRefCase11.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
#include "test_data/staticRefCase12.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
#include "test_data/staticRefCase13.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
#include "test_data/staticRefCase14.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
#include "test_data/staticRefCase15.h"
#endif

static VXLIB_accumulateWeightImage_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case2,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case2,      // Input vector 1
        staticRefOutCase2,      // Output vector
        VXLIB_UINT8,            // data type out
        0.21508218321450678,    // Alpha scalar
        256,                    // width of image
        256,                    // height of image
        256 * sizeof(uint8_t),  // strideIn0
        256 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        2,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case3,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case3,      // Input vector 1
        staticRefOutCase3,      // Output vector
        VXLIB_UINT8,            // data type out
        0.8190765589997907,     // Alpha scalar
        128,                    // width of image
        128,                    // height of image
        128 * sizeof(uint8_t),  // strideIn0
        128 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        3,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case4,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case4,      // Input vector 1
        staticRefOutCase4,      // Output vector
        VXLIB_UINT8,            // data type out
        0.39104880925624197,    // Alpha scalar
        64,                     // width of image
        64,                     // height of image
        64 * sizeof(uint8_t),   // strideIn0
        64 * sizeof(uint8_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        4,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case5,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case5,      // Input vector 1
        staticRefOutCase5,      // Output vector
        VXLIB_UINT8,            // data type out
        0.5630913213713418,     // Alpha scalar
        32,                     // width of image
        32,                     // height of image
        32 * sizeof(uint8_t),   // strideIn0
        32 * sizeof(uint8_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        5,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case6,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case6,      // Input vector 1
        staticRefOutCase6,      // Output vector
        VXLIB_UINT8,            // data type out
        0.8039203248964069,     // Alpha scalar
        16,                     // width of image
        16,                     // height of image
        16 * sizeof(uint8_t),   // strideIn0
        16 * sizeof(uint8_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        6,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 7))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case7,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case7,      // Input vector 1
        staticRefOutCase7,      // Output vector
        VXLIB_UINT8,            // data type out
        0.35211616407095336,    // Alpha scalar
        8,                      // width of image
        8,                      // height of image
        8 * sizeof(uint8_t),    // strideIn0
        8 * sizeof(uint8_t),    // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        7,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 8))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case8,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case8,      // Input vector 1
        staticRefOutCase8,      // Output vector
        VXLIB_UINT8,            // data type out
        0.7719221010153755,     // Alpha scalar
        128,                    // width of image
        32,                     // height of image
        160 * sizeof(uint8_t),  // strideIn0
        160 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        8,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 9))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case9,      // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case9,      // Input vector 1
        staticRefOutCase9,      // Output vector
        VXLIB_UINT8,            // data type out
        0.7005366628282758,     // Alpha scalar
        130,                    // width of image
        32,                     // height of image
        178 * sizeof(uint8_t),  // strideIn0
        178 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        9,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 10))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case10,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case10,     // Input vector 1
        staticRefOutCase10,     // Output vector
        VXLIB_UINT8,            // data type out
        0.14942369927720933,    // Alpha scalar
        78,                     // width of image
        32,                     // height of image
        78 * sizeof(uint8_t),   // strideIn0
        100 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        10,                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 11))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case11,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case11,     // Input vector 1
        staticRefOutCase11,     // Output vector
        VXLIB_UINT8,            // data type out
        0.41152886498311236,    // Alpha scalar
        128,                    // width of image
        64,                     // height of image
        160 * sizeof(uint8_t),  // strideIn0
        178 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        11,                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 12))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case12,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case12,     // Input vector 1
        staticRefOutCase12,     // Output vector
        VXLIB_UINT8,            // data type out
        0.21870426839839696,    // Alpha scalar
        78,                     // width of image
        32,                     // height of image
        83 * sizeof(uint8_t),   // strideIn0
        100 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        12,                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 13))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case13,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case13,     // Input vector 1
        staticRefOutCase13,     // Output vector
        VXLIB_UINT8,            // data type out
        0.22856637437941263,    // Alpha scalar
        1,                      // width of image
        2,                      // height of image
        1 * sizeof(uint8_t),    // strideIn0
        1 * sizeof(uint8_t),    // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        13,                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 14))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case14,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case14,     // Input vector 1
        staticRefOutCase14,     // Output vector
        VXLIB_UINT8,            // data type out
        0.8578074186955764,     // Alpha scalar
        1,                      // width of image
        1,                      // height of image
        32 * sizeof(uint8_t),   // strideIn0
        128 * sizeof(uint8_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        14,                     // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 15))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case15,     // Input vector 0
        VXLIB_UINT8,            // data type in0
        staticRefIn1Case15,     // Input vector 1
        staticRefOutCase15,     // Output vector
        VXLIB_UINT8,            // data type out
        0.4515271650447531,     // Alpha scalar
        3,                      // width of image
        3,                      // height of image
        64 * sizeof(uint8_t),   // strideIn0
        16 * sizeof(uint8_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        15,                     // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void VXLIB_accumulateWeightImage_getTestParams(VXLIB_accumulateWeightImage_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(VXLIB_accumulateWeightImage_testParams_t);
}
