// Copyright (C) 2026 Texas Instruments Incorporated
//
// SPDX-License-Identifier: Apache-2.0

#include "VXLIB_magnitude_idat.h"
/*This file is autogenerated*/
/*Please do not edit*/

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
#include "test_data/staticRefCase1.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
#include "test_data/staticRefCase2.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
#include "test_data/staticRefCase3.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
#include "test_data/staticRefCase4.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
#include "test_data/staticRefCase5.h"
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
#include "test_data/staticRefCase6.h"
#endif

static VXLIB_magnitude_testParams_t testParams[] = {
#if (defined(ALL_TEST_CASES) || (TEST_CASE == 1))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case1,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case1,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase1,      // Output vector
        VXLIB_INT16,            // data type out
        32,                     // width of image
        32,                     // height of image
        32 * sizeof(int16_t),   // strideIn0
        32 * sizeof(int16_t),   // strideIn1
        32 * sizeof(int16_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        1,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 2))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case2,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case2,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase2,      // Output vector
        VXLIB_INT16,            // data type out
        64,                     // width of image
        64,                     // height of image
        64 * sizeof(int16_t),   // strideIn0
        64 * sizeof(int16_t),   // strideIn1
        64 * sizeof(int16_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        2,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 3))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case3,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case3,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase3,      // Output vector
        VXLIB_INT16,            // data type out
        128,                    // width of image
        128,                    // height of image
        128 * sizeof(int16_t),  // strideIn0
        128 * sizeof(int16_t),  // strideIn1
        128 * sizeof(int16_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        3,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 4))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case4,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case4,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase4,      // Output vector
        VXLIB_INT16,            // data type out
        256,                    // width of image
        256,                    // height of image
        256 * sizeof(int16_t),  // strideIn0
        256 * sizeof(int16_t),  // strideIn1
        256 * sizeof(int16_t),  // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        4,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 5))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case5,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case5,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase5,      // Output vector
        VXLIB_INT16,            // data type out
        3,                      // width of image
        33,                     // height of image
        48 * sizeof(int16_t),   // strideIn0
        48 * sizeof(int16_t),   // strideIn1
        48 * sizeof(int16_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        5,                      // test ID
    },
#endif

#if (defined(ALL_TEST_CASES) || (TEST_CASE == 6))
    {
        STATIC,                 // Test pattern
        staticRefIn0Case6,      // Input vector 0
        VXLIB_INT16,            // data type in0
        staticRefIn1Case6,      // Input vector 1
        VXLIB_INT16,            // data type in1
        staticRefOutCase6,      // Output vector
        VXLIB_INT16,            // data type out
        32,                     // width of image
        32,                     // height of image
        32 * sizeof(int16_t),   // strideIn0
        64 * sizeof(int16_t),   // strideIn1
        64 * sizeof(int16_t),   // strideOut
        VXLIB_TEST_OUTPUT_MSMC, // Output data location
        1,                      // number of reps.
        6,                      // test ID
    },
#endif

};

/*
 *  Sends the test parameter structure and number of tests
 */
void VXLIB_magnitude_getTestParams(VXLIB_magnitude_testParams_t** params, int32_t* numTests)
{
   *params   = testParams;
   *numTests = sizeof(testParams) / sizeof(VXLIB_magnitude_testParams_t);
}
